version: 2
jobs:
  build:
    docker: 
      - image: davidva/usync
        auth:
         username: $U_NAME  
         password: $D_PASS
    working_directory: ~/enjoy
    no_output_timeout: 40m
    parallelism: 1
    steps:
      - checkout
      - run: " cd / && rm -f /united-build && /usr/bin/wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/sync-united && chmod a+x $PWD/sync-united && ./sync-united -s 26" 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/8ff0b35066468a87de71

        


