version: 2
jobs:
  build:
    docker: 
      - image: davidva/usync
        auth:
        username: $U_NAME
        password: $D_PASS	
    working_directory: ~
    parallelism: 1
    steps:
      - checkout
      - run: " cd / rm -rf united-build && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/sync-united && chmod a+x sync-united && ./sync-united -s 29" 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/8ff0b35066468a87de71

        


